spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:account?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sa
    password:

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
